<a href="https://colab.research.google.com/github/Claudio-Ferriz/Proyecto-de-Violencia-de-Genero-Digital/blob/main/Proyecto_Datos_y_G%C3%A9nero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importación y ejecución de las librerías de Python para el análisis y modelado
# de datos.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Generación del dataframe referido a Silencios Digitales el cual
# se encuentra en formato excel importando desde el repositorio
# github del proyecto.


df_sd = pd.read_excel('https://github.com/Claudio-Ferriz/Proyecto-de-Violencia-de-Genero-Digital/raw/refs/heads/main/BBDD%20Silencios%20Digitales%20(compartida%20UBA).xlsx')

# Eliminación de las columnas 'Unnamed' ya que no generan valor al df_ap.

#unnamed_cols = [col for col in df_ap.columns if col.startswith('Unnamed')]

#df_ap = df_ap.drop(columns=unnamed_cols)

df_sd

,Marca temporal,1. Edad,2. ¿En qué provincia vivís?,"3. ¿Cuántas horas por día usás internet, en promedio?",4. ¿Qué plataformas usás con mayor frecuencia en tu tiempo libre? (Marcá todas las opciones que correspondan) NO INCLUYAS LAS QUE USES PARA TRABAJAR - SOLO TIEMPO LIBRE,"5. Si usas instagram, tu perfil es",6. ¿Para qué usás redes sociales? (Marcá todas las opciones que correspondan),7. ¿Qué tan libre te sentís de publicar lo que querés en redes sociales o plataformas digitales? (Marcá todas las opciones que correspondan),8. ¿Cuál es tu máximo nivel educativo alcanzado?,9. ¿Con qué identidad de género te identificás?,...,25. ¿Realizaste cambios en el comportamiento digital después de lo sucedido? (Marcá todas las opciones que correspondan),26. ¿Qué efectos tuvo en vos haber vivido estas situaciones?,27. ¿Contaste lo sucedido a alguien?,"29. ¿Sabés cómo denunciar situaciones de violencia de género digital (en plataformas, instituciones o con apoyo legal)?","28. Realizaste alguna formación o te interiorizaste sobre seguridad digital en los últimos cinco años (por ejemplo, privacidad, contraseñas, configuración de cuentas)?",29. ¿Qué tipo de medidas te parecerían útiles para prevenir o responder a la violencia de género digital? (Marcá todas las opciones que correspondan),"30. ¿Cuánto sabés o entendés sobre las siguientes medidas de seguridad digital? (Contraseñas seguras, autenticación en dos pasos o doble factor (2FA), Redes privadas virtuales (VPN), etc?\n","31. Si alguna vez sufrieras una agresión en internet, ¿sentís que estás preparadx para proteger tu privacidad?",32. ¿Te gustaría contarnos algo más en torno a tus vivencias en internet y la violencia de género facilitada por la tecnología?,"33. Si querés recibir el informe con los resultados de la encuesta, compartinos tu correo electrónico"
0,2025-09-12 13:36:43.356,26,Santiago del Estero,Entre 2 y 3 horas,"WhatsApp, Instagram, Youtube, Chat GPT / Gemin...",Público y uso mejores amigos para cuestiones p...,Para difundir actividades laborales o profesio...,Evito publicar sobre ciertos temas porque ya h...,Terciario completo,Mujer,...,Eliminé cuentas o perfiles,Me dio miedo y sobre todo asco por los conteni...,"Sí a mi espacio de militancia, activismo",No,Si,Capacitaciones para mejorar el manejo de confi...,3.0,Si,Además de recibir constantes fotos de miembros...,NaN
1,2025-09-12 08:58:43.244,52,Ciudad Autónoma de Buenos Aires (CABA),Entre 4 y 5 horas,"WhatsApp, Instagram, Youtube, Chat GPT / Gemin...",Privado,Para difundir actividades laborales o profesio...,Evito publicar sobre política para no polemiza...,Posgrado completo,Mujer,...,NaN,NaN,NaN,Si,Si,Mayor control y respuesta por parte de las pla...,5.0,Parcialmente,NaN,NaN
2,2025-09-11 19:35:41.708,28,Ciudad Autónoma de Buenos Aires (CABA),Entre 5 y 6 horas,"WhatsApp, Instagram, TikTok, Youtube",Privado,Para divertirme y despejarme,Evito publicar sobre política por temor a repe...,Universitario incompleto,Mujer,...,NaN,NaN,NaN,No,No,Capacitaciones para mejorar el manejo de confi...,2.0,No,NaN,NaN
3,2025-09-11 12:55:54.372,26,Ciudad Autónoma de Buenos Aires (CABA),Más de 6 horas,"WhatsApp, Instagram, Youtube, Correo electrónico",Privado,"Para divertirme y despejarme, Para conectar co...",Evito publicar sobre política para no polemiza...,Universitario incompleto,Varón,...,NaN,NaN,NaN,No,No estoy segurx,Capacitaciones para mejorar el manejo de confi...,3.0,Parcialmente,NaN,NaN
4,2025-09-11 12:52:37.716,34,Ciudad Autónoma de Buenos Aires (CABA),Entre 1 y 2 horas,"WhatsApp, Instagram, Facebook, Youtube",Público,Para divertirme y despejarme,Evito publicar sobre política por temor a repe...,Universitario incompleto,Varón,...,No realicé cambios,"Entre amigos algunos chistes pueden pasar, no ...","No, no se lo conté a nadie",No,No,"Campañas de concientización y prevención, Mayo...",4.0,Parcialmente,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,2025-11-29 07:19:05.984,43,Buenos Aires,Entre 3 y 4 horas,"Instagram, Youtube",Privado,Para divertirme y despejarme,Me cuesta mucho mostrar mi cuerpo por no ser h...,Posgrado completo,Mujer,...,NaN,NaN,NaN,No estoy segurx,Si,Capacitaciones para mejorar el manejo de confi...,2.0,Parcialmente,NaN,NaN
1418,2025-11-29 07:25:37.466,43,Ciudad Autónoma de Buenos Aires (CABA),Entre 4 y 5 horas,"WhatsApp, Facebook, Youtube, Correo electrónico",Público,"Para divertirme y despejarme, Para difundir ac...",Evito publicar sobre política por temor a repe...,Posgrado completo,Mujer,...,Cambie foto de perfil. Ya no tengo una foto pr...,Desgastante,"Sí, a mi pareja",No,No,Acceso gratuito a apoyo legal y psicológico,3.0,No estoy segurx,NaN,NaN
1419,2025-11-29 07:36:39.413,42,Neuquén,Más de 6 horas,"WhatsApp, Instagram, Facebook, Youtube, Apps d...",Privado,Para divertirme y despejarme,Evito publicar sobre política para no polemiza...,Terciario completo,Mujer,...,No realicé cambios,Empecé a desconfiar de esa persona y a sentirm...,"No, no se lo conté a nadie",No,No,Capacitaciones para mejorar el manejo de confi...,1.0,No,Las aplicaciones de citas son un horror,NaN
1420,2025-11-29 07:42:48.145,31,Río Negro,Entre 3 y 4 horas,"WhatsApp, Instagram, Youtube",Privado,"Para divertirme y despejarme, Para difundir ac...",Casi no uso redes sociales y por ende no publi...,Terciario completo,Mujer,...,NaN,NaN,NaN,Si,No,Mayor control y respuesta por parte de las pla...,2.0,Parcialmente,Entre el 2020 y el 2022 me acosó un ex desde B...,NaN
1421,2025-11-29 08:04:09.824,39,Buenos Aires,Entre 4 y 5 horas,"WhatsApp, Instagram, Facebook, Youtube, Juegos...",Público y uso mejores amigos para cuestiones p...,"Para divertirme y despejarme, Para difundir ac...",Evito publicar sobre política para no polemiza...,Universitario completo,Mujer,...,Me censuré o dejé de publicar ciertos tipos de...,Dejé de sentirme libre de comentar lo que quer...,"Sí, a mi pareja",Si,No,Capacitaciones para mejorar el manejo de confi...,4.0,Parcialmente,Dejé de jugar videojuegos online por el acoso ...,NaN

In [3]:
df_sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1422 entries, 0 to 1421
Data columns (total 35 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              --------------  -----
 0   Marca temporal                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1422 non-null   datetime64[ns]
 1   1. Edad                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1422 non-null   object
 2   2. ¿En qué provincia vivís?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1422 non-null   object
 3   3. ¿Cuántas horas por día usás internet, en promedio?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1422 non-null   object
 4   4. ¿Qué plataformas usás con mayor frecuencia en tu tiempo libre?  (Marcá todas las opciones que correspondan) NO INCLUYAS LAS QUE USES PARA TRABAJAR - SOLO TIEMPO LIBRE                                                                                                                                                                                                                                                                                                                                                                                                                                           1422 non-null   object
 5   5. Si usas instagram, tu perfil es                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1371 non-null   object
 6   6. ¿Para qué usás redes sociales?  (Marcá todas las opciones que correspondan)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1422 non-null   object
 7   7. ¿Qué tan libre te sentís de publicar lo que querés en redes sociales o plataformas digitales? (Marcá todas las opciones que correspondan)                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1422 non-null   object
 8   8. ¿Cuál es tu máximo nivel educativo alcanzado?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1422 non-null   object
 9   9. ¿Con qué identidad de género te identificás?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1422 non-null   object
 10  10. ¿Cuál es tu orientación sexual?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1422 non-null   object
 11  11. ¿Participás o militás en alguna organización política, social o colectiva? (Marcar todas las opciones que correspondan)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1422 non-null   object
 12  12. ¿Cuál de estas situaciones describe mejor tu realidad económica actual?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1422 non-null   object
 13  13. En los últimos 24 meses, ¿viviste algún intento de estafa?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1422 non-null   object
 14  14. ¿En los grupos de WhatsApp o Telegram en los que participás, circulan chistes, comentarios, imágenes o stickers que incluyan alguno de los siguientes contenidos? (Marcá todas las opciones que correspondan)                                                                                                                                                                                                                                                                                                                                                                                                   1422 non-null   object
 15  15. ¿En los últimos 24 meses, sufriste alguna situación de violencia de género en entornos digitales?

La violencia de género facilitada por la tecnología es cualquier conducta dirigida contra mujeres, niñas y otras personas en razón de su orientación sexual, identidad o expresión de género que cause daño y que sea cometida, facilitada o amplificada mediante el uso de tecnologías de la información y la comunicación (TIC).
Este tipo de violencia incluye, la difusión no consentida de imágenes íntimas, las agresiones verbales en plataformas y el acoso virtual, amenazas, entre otras formas.  1422 non-null   object
 16  16. ¿En los últimos 24 meses, viviste alguna de las siguientes situaciones en entornos digitales? (Marcá todas las opciones que correspondan)                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1422 non-null   object
 17  17. ¿En la pregunta anterior marcaste al menos una de las situaciones mencionadas?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1422 non-null   object
 18  18. ¿En qué espacios o plataformas ocurrió esta situación?  Si seleccionaste más de una situación en la pregunta anterior, te pedimos que a partir de ahora respondas pensando en aquella situación que te haya resultado más difícil o significativa.                                                                                                                                                                                                                                                                                                                                                              571 non-null    object
 19  19. ¿Sentís que la situación que viviste estuvo motivada por...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     571 non-null    object
 20  20. ¿Conocías a la persona o grupo que llevó adelante esta acción?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  571 non-null    object
 21  21. ¿Qué vínculo tenés/tenías vos con esa persona?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  223 non-null    object
 22  22. Más allá de lo que ocurrió en entornos digitales, ¿pasaron algunas de estas situaciones con tu pareja o ex pareja?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              55 non-null     object
 23  23. ¿Denunciaste la situación? (Marcá todas las opciones que correspondan)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          571 non-null    object
 24  24. ¿Cómo describirías la situación de violencia que viviste?  (Marcá todas las opciones que correspondan)
Recordá que tu respuesta es sobre la situación que te haya resultado más difícil o significativa.                                                                                                                                                                                                                                                                                                                                                                                                       571 non-null    object
 25  25. ¿Realizaste cambios en el comportamiento digital después de lo sucedido? (Marcá todas las opciones que correspondan)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            571 non-null    object
 26  26.  ¿Qué efectos tuvo en vos haber vivido estas situaciones?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       414 non-null    object
 27  27.  ¿Contaste lo sucedido a alguien?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               571 non-null    object
 28  29. ¿Sabés cómo denunciar situaciones de violencia de género digital  (en plataformas, instituciones o con apoyo legal)?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1422 non-null   object

In [6]:
df_sd.columns.to_list()

['Marca temporal',
 '1. Edad',
 '2. ¿En qué provincia vivís?',
 '3. ¿Cuántas horas por día usás internet, en promedio?',
 '4. ¿Qué plataformas usás con mayor frecuencia en tu tiempo libre?  (Marcá todas las opciones que correspondan) NO INCLUYAS LAS QUE USES PARA TRABAJAR - SOLO TIEMPO LIBRE',
 '5. Si usas instagram, tu perfil es',
 '6. ¿Para qué usás redes sociales?  (Marcá todas las opciones que correspondan)',
 '7. ¿Qué tan libre te sentís de publicar lo que querés en redes sociales o plataformas digitales? (Marcá todas las opciones que correspondan)',
 '8. ¿Cuál es tu máximo nivel educativo alcanzado?',
 '9. ¿Con qué identidad de género te identificás?',
 '10. ¿Cuál es tu orientación sexual?',
 '11. ¿Participás o militás en alguna organización política, social o colectiva? (Marcar todas las opciones que correspondan) ',
 '12. ¿Cuál de estas situaciones describe mejor tu realidad económica actual?',
 '13. En los últimos 24 meses, ¿viviste algún intento de estafa?',
 '14. ¿En los grupos de WhatsApp o Telegram en los que participás, circulan chistes, comentarios, imágenes o stickers que incluyan alguno de los siguientes contenidos? (Marcá todas las opciones que correspondan)  ',
 '15. ¿En los últimos 24 meses, sufriste alguna situación de violencia de género en entornos digitales? \n\nLa violencia de género facilitada por la tecnología es cualquier conducta dirigida contra mujeres, niñas y otras personas en razón de su orientación sexual, identidad o expresión de género que cause daño y que sea cometida, facilitada o amplificada mediante el uso de tecnologías de la información y la comunicación (TIC).\nEste tipo de violencia incluye, la difusión no consentida de imágenes íntimas, las agresiones verbales en plataformas y el acoso virtual, amenazas, entre otras formas.',
 '16. ¿En los últimos 24 meses, viviste alguna de las siguientes situaciones en entornos digitales? (Marcá todas las opciones que correspondan)  ',
 '17. ¿En la pregunta anterior marcaste al menos una de las situaciones mencionadas?',
 '18. ¿En qué espacios o plataformas ocurrió esta situación?  Si seleccionaste más de una situación en la pregunta anterior, te pedimos que a partir de ahora respondas pensando en aquella situación que te haya resultado más difícil o significativa.',
 '19. ¿Sentís que la situación que viviste estuvo motivada por...',
 '20. ¿Conocías a la persona o grupo que llevó adelante esta acción?',
 '21. ¿Qué vínculo tenés/tenías vos con esa persona?',
 '22. Más allá de lo que ocurrió en entornos digitales, ¿pasaron algunas de estas situaciones con tu pareja o ex pareja? ',
 '23. ¿Denunciaste la situación? (Marcá todas las opciones que correspondan)',
 '24. ¿Cómo describirías la situación de violencia que viviste?  (Marcá todas las opciones que correspondan) \nRecordá que tu respuesta es sobre la situación que te haya resultado más difícil o significativa.',
 '25. ¿Realizaste cambios en el comportamiento digital después de lo sucedido? (Marcá todas las opciones que correspondan)',
 '26.  ¿Qué efectos tuvo en vos haber vivido estas situaciones? ',
 '27.  ¿Contaste lo sucedido a alguien? ',
 '29. ¿Sabés cómo denunciar situaciones de violencia de género digital  (en plataformas, instituciones o con apoyo legal)?  ',
 '28. Realizaste alguna formación o te interiorizaste sobre seguridad digital en los últimos cinco años (por ejemplo, privacidad, contraseñas, configuración de cuentas)?',
 '29. ¿Qué tipo de medidas te parecerían útiles para prevenir o responder a la violencia de género digital? (Marcá todas las opciones que correspondan)',
 '30. ¿Cuánto sabés o entendés sobre las siguientes medidas de seguridad digital?   (Contraseñas seguras, autenticación en dos pasos o doble factor (2FA),  Redes privadas virtuales (VPN), etc?\n',
 '31. Si alguna vez sufrieras una agresión en internet, ¿sentís que estás preparadx para proteger tu privacidad?',
 '32. ¿Te gustaría contarnos algo más en torno a tus vivencias en internet y la violencia de género facilitada por la tecnología?',
 '33. Si querés recibir el informe con los resultados de la encuesta, compartinos tu correo electrónico ']

In [11]:
df_sd = df_sd.rename(columns={'1. Edad':'Edad','2. ¿En qué provincia vivís?':'Provincia','3. ¿Cuántas horas por día usás internet, en promedio?':'Uso promedio en horas por día de internet',
 '4. ¿Qué plataformas usás con mayor frecuencia en tu tiempo libre?  (Marcá todas las opciones que correspondan) NO INCLUYAS LAS QUE USES PARA TRABAJAR - SOLO TIEMPO LIBRE':'Plataforma más utilizada en el tiempo libre',
 '5. Si usas instagram, tu perfil es':'Tipo de perfil en Instagram',
 '6. ¿Para qué usás redes sociales?  (Marcá todas las opciones que correspondan)':'Uso de las redes sociales',
 '7. ¿Qué tan libre te sentís de publicar lo que querés en redes sociales o plataformas digitales? (Marcá todas las opciones que correspondan)':'Nivel de libertas para publicar en redes sociales o plataformas digitales',
 '8. ¿Cuál es tu máximo nivel educativo alcanzado?':'Nivel educativo alcanzado',
 '9. ¿Con qué identidad de género te identificás?':'Género',
 '10. ¿Cuál es tu orientación sexual?':'Orientación sexual',
 '11. ¿Participás o militás en alguna organización política, social o colectiva? (Marcar todas las opciones que correspondan) ':'Participación o militancia en organizaciones políticas, sociales o colectivas',
 '12. ¿Cuál de estas situaciones describe mejor tu realidad económica actual?':'Situación económica',
 '13. En los últimos 24 meses, ¿viviste algún intento de estafa?':'Intento de estafa en los últimos 24 meses',
 '14. ¿En los grupos de WhatsApp o Telegram en los que participás, circulan chistes, comentarios, imágenes o stickers que incluyan alguno de los siguientes contenidos? (Marcá todas las opciones que correspondan)  ':'Circulación de chistes, comentarios, imágenes o stickers en grupos de WhatsApp o Telegram',
 '15. ¿En los últimos 24 meses, sufriste alguna situación de violencia de género en entornos digitales? \n\nLa violencia de género facilitada por la tecnología es cualquier conducta dirigida contra mujeres, niñas y otras personas en razón de su orientación sexual, identidad o expresión de género que cause daño y que sea cometida, facilitada o amplificada mediante el uso de tecnologías de la información y la comunicación (TIC).\nEste tipo de violencia incluye, la difusión no consentida de imágenes íntimas, las agresiones verbales en plataformas y el acoso virtual, amenazas, entre otras formas.':'Situación de violencia de género en entornos digitales sufrida en los últimos 24 meses',
 '16. ¿En los últimos 24 meses, viviste alguna de las siguientes situaciones en entornos digitales? (Marcá todas las opciones que correspondan)  ': 'Situaciones de violencia de género en entornos digitales sufridas en los últimos 24 meses',
 '17. ¿En la pregunta anterior marcaste al menos una de las situaciones mencionadas?':'Si vivio o no alguna situación de violencia de género en entornos digitales',
 '18. ¿En qué espacios o plataformas ocurrió esta situación?  Si seleccionaste más de una situación en la pregunta anterior, te pedimos que a partir de ahora respondas pensando en aquella situación que te haya resultado más difícil o significativa.':'Espacios o plataformas donde ocurren estas situaciones',
 '19. ¿Sentís que la situación que viviste estuvo motivada por...':'Motivo de la situación vivida',
 '20. ¿Conocías a la persona o grupo que llevó adelante esta acción?':'Si existe conocimiento de la persona o grupo que llevo a cabo la acción',
 '21. ¿Qué vínculo tenés/tenías vos con esa persona?':'Vínculo qué tiene/tenía con esa persona',
 '22. Más allá de lo que ocurrió en entornos digitales, ¿pasaron algunas de estas situaciones con tu pareja o ex pareja? ':'Situaciones de violencia de género en entornos digitales con pareja o ex pareja',
 '23. ¿Denunciaste la situación? (Marcá todas las opciones que correspondan)': 'Denuncia de la situación',
 '24. ¿Cómo describirías la situación de violencia que viviste?  (Marcá todas las opciones que correspondan) \nRecordá que tu respuesta es sobre la situación que te haya resultado más difícil o significativa.':'Descripción de la situación de violencia vivida',
 '25. ¿Realizaste cambios en el comportamiento digital después de lo sucedido? (Marcá todas las opciones que correspondan)':'Cambios en el comportamiento digital luego de lo sucedido',
 '26.  ¿Qué efectos tuvo en vos haber vivido estas situaciones? ':'Efectos de haber vivido estas situaciones de violencia',
 '27.  ¿Contaste lo sucedido a alguien? ': 'Si conto lo sucedido a alguien',
 '29. ¿Sabés cómo denunciar situaciones de violencia de género digital  (en plataformas, instituciones o con apoyo legal)?  ':'Si sabe como denunciar situaciones de violencia de género digital',
 '28. Realizaste alguna formación o te interiorizaste sobre seguridad digital en los últimos cinco años (por ejemplo, privacidad, contraseñas, configuración de cuentas)?':'Si Realizo alguna formación o se interiorizo sobre seguridad digital en los últimos cinco años',
 '29. ¿Qué tipo de medidas te parecerían útiles para prevenir o responder a la violencia de género digital? (Marcá todas las opciones que correspondan)':'Tipo de medidas útiles para prevenir o responder a la violencia de género digital',
 '30. ¿Cuánto sabés o entendés sobre las siguientes medidas de seguridad digital?   (Contraseñas seguras, autenticación en dos pasos o doble factor (2FA),  Redes privadas virtuales (VPN), etc?\n':'Nivel de conocimiento o entendimiento de medidas de seguridad digital',
 '31. Si alguna vez sufrieras una agresión en internet, ¿sentís que estás preparadx para proteger tu privacidad?':' Nivel de preparación para proteger su privacidad',
 '32. ¿Te gustaría contarnos algo más en torno a tus vivencias en internet y la violencia de género facilitada por la tecnología?':'Vivencias en internet y violencia de género facilitada por la tecnología',
 '33. Si querés recibir el informe con los resultados de la encuesta, compartinos tu correo electrónico':'Si quiere recibir el informe con los resultados de la encuesta vía correo electrónico'})

df_sd

,Marca temporal,Edad,Provincia,Uso promedio de horas por día en internet,Plataforma más utilizada en el tiempo libre,Tipo de perfil en Instagram,Uso de las redes sociales,Nivel de libertas para publicar en redes sociales o plataformas digitales,Nivel educativo alcanzado,Género,...,Cambios en el comportamiento digital luego de lo sucedido,Efectos de haber vivido estas situaciones de violencia,Si conto lo sucedido a alguien,Si sabe como denunciar situaciones de violencia de género digital,Si Realizo alguna formación o se interiorizo sobre seguridad digital en los últimos cinco años,Tipo de medidas útiles para prevenir o responder a la violencia de género digital,Nivel de conocimiento o entendimiento de medidas de seguridad digital,Nivel de preparación para proteger su privacidad,Vivencias en internet y violencia de género facilitada por la tecnología,"33. Si querés recibir el informe con los resultados de la encuesta, compartinos tu correo electrónico"
0,2025-09-12 13:36:43.356,26,Santiago del Estero,Entre 2 y 3 horas,"WhatsApp, Instagram, Youtube, Chat GPT / Gemin...",Público y uso mejores amigos para cuestiones p...,Para difundir actividades laborales o profesio...,Evito publicar sobre ciertos temas porque ya h...,Terciario completo,Mujer,...,Eliminé cuentas o perfiles,Me dio miedo y sobre todo asco por los conteni...,"Sí a mi espacio de militancia, activismo",No,Si,Capacitaciones para mejorar el manejo de confi...,3.0,Si,Además de recibir constantes fotos de miembros...,NaN
1,2025-09-12 08:58:43.244,52,Ciudad Autónoma de Buenos Aires (CABA),Entre 4 y 5 horas,"WhatsApp, Instagram, Youtube, Chat GPT / Gemin...",Privado,Para difundir actividades laborales o profesio...,Evito publicar sobre política para no polemiza...,Posgrado completo,Mujer,...,NaN,NaN,NaN,Si,Si,Mayor control y respuesta por parte de las pla...,5.0,Parcialmente,NaN,NaN
2,2025-09-11 19:35:41.708,28,Ciudad Autónoma de Buenos Aires (CABA),Entre 5 y 6 horas,"WhatsApp, Instagram, TikTok, Youtube",Privado,Para divertirme y despejarme,Evito publicar sobre política por temor a repe...,Universitario incompleto,Mujer,...,NaN,NaN,NaN,No,No,Capacitaciones para mejorar el manejo de confi...,2.0,No,NaN,NaN
3,2025-09-11 12:55:54.372,26,Ciudad Autónoma de Buenos Aires (CABA),Más de 6 horas,"WhatsApp, Instagram, Youtube, Correo electrónico",Privado,"Para divertirme y despejarme, Para conectar co...",Evito publicar sobre política para no polemiza...,Universitario incompleto,Varón,...,NaN,NaN,NaN,No,No estoy segurx,Capacitaciones para mejorar el manejo de confi...,3.0,Parcialmente,NaN,NaN
4,2025-09-11 12:52:37.716,34,Ciudad Autónoma de Buenos Aires (CABA),Entre 1 y 2 horas,"WhatsApp, Instagram, Facebook, Youtube",Público,Para divertirme y despejarme,Evito publicar sobre política por temor a repe...,Universitario incompleto,Varón,...,No realicé cambios,"Entre amigos algunos chistes pueden pasar, no ...","No, no se lo conté a nadie",No,No,"Campañas de concientización y prevención, Mayo...",4.0,Parcialmente,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,2025-11-29 07:19:05.984,43,Buenos Aires,Entre 3 y 4 horas,"Instagram, Youtube",Privado,Para divertirme y despejarme,Me cuesta mucho mostrar mi cuerpo por no ser h...,Posgrado completo,Mujer,...,NaN,NaN,NaN,No estoy segurx,Si,Capacitaciones para mejorar el manejo de confi...,2.0,Parcialmente,NaN,NaN
1418,2025-11-29 07:25:37.466,43,Ciudad Autónoma de Buenos Aires (CABA),Entre 4 y 5 horas,"WhatsApp, Facebook, Youtube, Correo electrónico",Público,"Para divertirme y despejarme, Para difundir ac...",Evito publicar sobre política por temor a repe...,Posgrado completo,Mujer,...,Cambie foto de perfil. Ya no tengo una foto pr...,Desgastante,"Sí, a mi pareja",No,No,Acceso gratuito a apoyo legal y psicológico,3.0,No estoy segurx,NaN,NaN
1419,2025-11-29 07:36:39.413,42,Neuquén,Más de 6 horas,"WhatsApp, Instagram, Facebook, Youtube, Apps d...",Privado,Para divertirme y despejarme,Evito publicar sobre política para no polemiza...,Terciario completo,Mujer,...,No realicé cambios,Empecé a desconfiar de esa persona y a sentirm...,"No, no se lo conté a nadie",No,No,Capacitaciones para mejorar el manejo de confi...,1.0,No,Las aplicaciones de citas son un horror,NaN
1420,2025-11-29 07:42:48.145,31,Río Negro,Entre 3 y 4 horas,"WhatsApp, Instagram, Youtube",Privado,"Para divertirme y despejarme, Para difundir ac...",Casi no uso redes sociales y por ende no publi...,Terciario completo,Mujer,...,NaN,NaN,NaN,Si,No,Mayor control y respuesta por parte de las pla...,2.0,Parcialmente,Entre el 2020 y el 2022 me acosó un ex desde B...,NaN
1421,2025-11-29 08:04:09.824,39,Buenos Aires,Entre 4 y 5 horas,"WhatsApp, Instagram, Facebook, Youtube, Juegos...",Público y uso mejores amigos para cuestiones p...,"Para divertirme y despejarme, Para difundir ac...",Evito publicar sobre política para no polemiza...,Universitario completo,Mujer,...,Me censuré o dejé de publicar ciertos tipos de...,Dejé de sentirme libre de comentar lo que quer...,"Sí, a mi pareja",Si,No,Capacitaciones para mejorar el manejo de confi...,4.0,Parcialmente,Dejé de jugar videojuegos online por el acoso ...,NaN

In [12]:
df_sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1422 entries, 0 to 1421
Data columns (total 35 columns):
 #   Column                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                  --------------  -----
 0   Marca temporal                                                                                          1422 non-null   datetime64[ns]
 1   Edad                                                                                                    1422 non-null   object
 2   Provincia                                                                                               1422 non-null   object
 3   Uso promedio de horas por día en internet                                                               1422 non-null   object
 4   Plataforma más utilizada en el tiempo libre                                                             1422 non-null   object
 5   Tipo de perfil en Instagram                                                                             1371 non-null   object
 6   Uso de las redes sociales                                                                               1422 non-null   object
 7   Nivel de libertas para publicar en redes sociales o plataformas digitales                               1422 non-null   object
 8   Nivel educativo alcanzado                                                                               1422 non-null   object
 9   Género                                                                                                  1422 non-null   object
 10  Orientación sexual                                                                                      1422 non-null   object
 11  Participación o militancia en organizaciones políticas, sociales o colectivas                           1422 non-null   object
 12  Situación económica                                                                                     1422 non-null   object
 13  Intento de estafa en los últimos 24 meses                                                               1422 non-null   object
 14  Circulación de chistes, comentarios, imágenes o stickers en grupos de WhatsApp o Telegram               1422 non-null   object
 15  Situación de violencia de género en entornos digitales sufrida en los últimos 24 meses                  1422 non-null   object
 16  Situaciones de violencia de género en entornos digitales sufridas en los últimos 24 meses               1422 non-null   object
 17  Si vivio o no alguna situación de violencia de género en entornos digitales                             1422 non-null   object
 18  Espacios o plataformas donde ocurren estas situaciones                                                  571 non-null    object
 19  Motivo de la situación vivida                                                                           571 non-null    object
 20  Si existe conocimiento de la persona o grupo que llevo a cabo la acción                                 571 non-null    object
 21  Vínculo qué tiene/tenía con esa persona                                                                 223 non-null    object
 22  Situaciones de violencia de género en entornos digitales con pareja o ex pareja                         55 non-null     object
 23  Denuncia de la situación                                                                                571 non-null    object
 24  Descripción de la situación de violencia vivida                                                         571 non-null    object
 25  Cambios en el comportamiento digital luego de lo sucedido                                               571 non-null    object
 26  Efectos de haber vivido estas situaciones de violencia                                                  414 non-null    object
 27  Si conto lo sucedido a alguien                                                                          571 non-null    object
 28  Si sabe como denunciar situaciones de violencia de género digital                                       1422 non-null   object
 29  Si Realizo alguna formación o se interiorizo sobre seguridad digital en los últimos cinco años          1422 non-null   object
 30  Tipo de medidas útiles para prevenir o responder a la violencia de género digital                       1422 non-null   object
 31  Nivel de conocimiento o entendimiento de medidas de seguridad digital                                   1415 non-null   float64
 32   Nivel de preparación para proteger su privacidad                                                       1422 non-null   object
 33  Vivencias en internet y violencia de género facilitada por la tecnología                                430 non-null    object
 34  33. Si querés recibir el informe con los resultados de la encuesta, compartinos tu correo electrónico   0 non-null      float64
dtypes: datetime64[ns](1), float64(2), object(32)
memory usage: 389.0+ KB